source "http://rubygems.org"

gem "sass", :git => "git://github.com/nex3/sass", :branch => "master"
gem "compass", :git => "git://github.com/chriseppstein/compass", :branch => "master"
gem "true", :git => "git://github.com/ericam/true", :branch => "master"

gem 'rb-fsevent', '~> 0.9'
