source "http://rubygems.org"

gem "sass", '~> 3.3.0.rc.1'
gem "compass", '~> 0.13.alpha.7'
# gem "true", :git => "git://github.com/ericam/true", :branch => "master"
gem "true", :path => "/Users/eric/Sites/true"

gem 'rb-fsevent', '~> 0.9'
