source "http://rubygems.org"

gem "sass", :git => 'git://github.com/nex3/sass.git', :branch => 'master'
gem "compass", :git => 'git://github.com/chriseppstein/compass.git', :branch => 'master'
gem "true", "~> 0.2.0.rc.4"
gem "breakpoint", "~> 2.4.0"
gem "susy", :path => ".."
