source "http://rubygems.org"

gem "middleman", "~> 3.1.3"
gem "sass", "~> 3.2.9"
gem "compass", "~> 0.12.2"
gem "susy", :path => "../"

gem "modular-scale", "~> 1.0.3"
gem "redcarpet"
gem "rack-codehighlighter", :git => "git://github.com/wbzyl/rack-codehighlighter.git"
gem "pygments.rb"
